---

version: '3.8'
services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myapppass
    volumes:
    - db-data:/var/lib/mysql
  php:
    build: ./php
    depends_on:
    - db
    # http://localhost:8562/ でサイト表示
    ports:
    - 8564:8000
    volumes:
    - ./work:/work

  # phpMyAdminコンテナを追加する
  pma:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_HOST=db
      - PMA_USER=myappuser
      - PMA_PASSWORD=myapppass
    ports:
      - 8090:80
    volumes:
      - pma-session-store:/sessions

volumes:
  db-data:
  pma-session-store:
